on: [push, pull_request]
name: Continuous Integration
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build-only-ios:
    name: Build only (iOS)
    # change to macos-latest once GitHub finishes migrating all repositories to macOS 12.
    runs-on: macos-12
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 30

      - name: get tags
        run: |
          git fetch --tags --force --depth 10
          echo ::set-output name=subject::$(git for-each-ref $GITHUB_REF --format='%(contents:subject)')

      - name: get version
        run: |
          echo "bver=$(git describe --tags --abbrev=0)" >> ${GITHUB_ENV}

      # see https://github.com/actions/runner-images/issues/6771#issuecomment-1354713617
      # remove once all workflow VMs use Xcode 14.1
      - name: Set Xcode Version
        shell: bash
        run: |
          sudo xcode-select -s "/Applications/Xcode_14.1.app"
          echo "MD_APPLE_SDK_ROOT=/Applications/Xcode_14.1.app" >> $GITHUB_ENV

      - name: Install .NET 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Install .NET Workloads
        run: dotnet workload install maui-ios

      - name: Build
        run: dotnet publish -f:net6.0-ios -c Release osu.iOS --output ./osu.iOS/bin /property:Version=${{ env.bver }}
      
      - name: upload stuff idk
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: osu-ios-build-${{ env.bver }}
          path: osu.iOS/bin/*.ipa