on: [push, pull_request]
name: Continuous Integration
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build-only-ios:
    name: Build only (iOS)
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 30

      - name: get tags
        run: |
          git fetch --tags --force --depth 10
          echo ::set-output name=subject::$(git for-each-ref $GITHUB_REF --format='%(contents:subject)')

      - name: get version
        run: |
          echo "bver=$(git describe --tags --abbrev=0)" >> ${GITHUB_ENV}
          echo "got version: $bver ${{ env.bver }}"

      - name: Install .NET 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      # Contrary to seemingly any other msbuild, msbuild running on macOS/Mono
      # cannot accept .sln(f) files as arguments.
      # Build just the main game for now.
      - name: Build
        run: msbuild osu.iOS/osu.iOS.csproj /restore /p:CFBundleVersion=${{ env.bver }} /p:VersionString=${{ env.bver }} /p:BuildIpa=True /p:Configuration=Release /p:Platform=iPhone

      - name: upload stuff idk
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: osu-ios-build-${{ env.bver }}
          path: osu.iOS/bin/iPhone/Release/*.ipa