on: [push, pull_request]
name: Continuous Integration
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build-only-ios:
    name: Build only (iOS)
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      # Contrary to seemingly any other msbuild, msbuild running on macOS/Mono
      # cannot accept .sln(f) files as arguments.
      # Build just the main game for now.
      - name: Build
        run: msbuild osu.iOS/osu.iOS.csproj /restore /p:BuildIpa=True /p:Configuration=Release,Platform=iPhone

      - name: upload stuff idk
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: osu-ios-build-${ github.ref }
          path: osu.iOS/bin